//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniHax.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniHax.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Bestfit&gt;
        ///  &lt;Mapping&gt;
        ///    &lt;Ascii&gt;0021&lt;/Ascii&gt;
        ///    &lt;Unicode&gt;00A8&lt;/Unicode&gt;
        ///    &lt;Name&gt;#&lt;/Name&gt;
        ///    &lt;Charset&gt;APL-ISO-IR-68&lt;/Charset&gt;
        ///  &lt;/Mapping&gt;
        ///  &lt;Mapping&gt;
        ///    &lt;Ascii&gt;0022&lt;/Ascii&gt;
        ///    &lt;Unicode&gt;0029&lt;/Unicode&gt;
        ///    &lt;Name&gt;#&lt;/Name&gt;
        ///    &lt;Charset&gt;APL-ISO-IR-68&lt;/Charset&gt;
        ///  &lt;/Mapping&gt;
        ///  &lt;Mapping&gt;
        ///    &lt;Ascii&gt;0023&lt;/Ascii&gt;
        ///    &lt;Unicode&gt;003C&lt;/Unicode&gt;
        ///    &lt;Name&gt;#&lt;/Name&gt;
        ///    &lt;Charset&gt;APL-ISO-IR-68&lt;/Charset&gt;
        ///  &lt;/Mapping&gt;
        ///  &lt;Mapping&gt;
        ///    &lt;Ascii&gt;0024&lt;/Ascii&gt;
        ///    &lt;Unicode&gt;2264&lt;/Unicode&gt;
        ///    &lt;Name&gt;#&lt;/Name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bestfit {
            get {
                return ResourceManager.GetString("bestfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Bestfit&gt;
        ///  &lt;Mapping&gt;
        ///    &lt;Ascii&gt;006A&lt;/Ascii&gt;
        ///    &lt;Unicode&gt;004A&lt;/Unicode&gt;
        ///    &lt;Name&gt;LATIN CAPITAL LETTER J&lt;/Name&gt;
        ///    &lt;Transform&gt;Simple_Lowercase_Mapping&lt;/Transform&gt;
        ///  &lt;/Mapping&gt;
        ///  &lt;Mapping&gt;
        ///    &lt;Ascii&gt;006A&lt;/Ascii&gt;
        ///    &lt;Unicode&gt;004A&lt;/Unicode&gt;
        ///    &lt;Name&gt;LATIN CAPITAL LETTER J&lt;/Name&gt;
        ///    &lt;Transform&gt;Lowercase_Mapping&lt;/Transform&gt;
        ///  &lt;/Mapping&gt;
        ///  &lt;Mapping&gt;
        ///    &lt;Ascii&gt;006A&lt;/Ascii&gt;
        ///    &lt;Unicode&gt;004A&lt;/Unicode&gt;
        ///    &lt;Name&gt;LATIN CAPITAL LETTER J&lt;/Name&gt;
        ///    &lt;Transform&gt;Simple_Case_Folding&lt;/Transform&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unicode {
            get {
                return ResourceManager.GetString("unicode", resourceCulture);
            }
        }
    }
}
